### ISSUE TITLE
HTTP 302 in line 48 of upload_to_kis.pl

### ISSUE THREAD

**Issue by sigma67** [mklemme1/hosteurope-letsencrypt#1]
Hey, I just tried your script and it worked fine, up until the part where the perl script is executed.

First, there is still an entry left left over from your custom code in line 25, which I deleted.
Second, I am receiving the 302 error after running the script. Do you know why this is happening?

Other than that, thank you very much for this useful script!

**Comment by mklemme1** [comment]
Thanks for the feedback.
I cleaned up the code and removed the remaining personal code.

**Comment by mklemme1** [comment]
Please try again
