### ISSUE TITLE
Upload nicht erfolgreich at ./upload_to_kis.pl line 59.

### ISSUE THREAD

**Issue by mackay2k4** [mklemme1/hosteurope-letsencrypt#2]
Hey,

ich versuche gerade das script zum laufen zu bringen. Doch leider kommt:
Upload nicht erfolgreich at ./upload_to_kis.pl line 59.
getssl: error running ./upload_to_kis.pl

Ich glaube es hängt mir dem login zusammen. Wenn ich mir den resonse_body ausgeben lasse kommt:
 ... ungültiger Login. Bitte beachten Sie: Nach drei falschen Eingaben sperren wir aus Sicherheitsgründen Ihren Account. ....
Ich habe überprüft ob er alle sonderzeichen richtig in den WWW::Curl zusammensetzt und das sieht im ersten moment gut aus.

für eine lösung wäre ich sehr dankbar.

mackay

**Comment by mklemme1** [comment]
Hallo,
Versuche, den URL direkt im Browser zu öffnen:
  `https://kis.hosteurope.de/administration/webhosting/admin.php?kdnummer=XXX&passwd=YYY`
Dann siehst Du, ob es an den Zugangsdaten liegt.
KIS_KDNUMMER ist nicht die Kundennummer, sondern der Benutzername des KIS.

Grüße
  M
