### ISSUE TITLE
path problems 

### ISSUE THREAD

**Issue by Don-Sheerwood** [mklemme1/hosteurope-letsencrypt#3]
**Hallo**
Zugegeben ich bin Neuling unter Linux aber ich habe mir echt Mühe gegeben das Script zu verstehenen und auf meinem Pi zum laufen zu bekommen. Irgendwie hab ich in der Ordnerstruktur einen Fehler:

pi@cloud-server:~/he $ bash ./run.sh
Tue 19 Jun 11:17:23 UTC 2018
rubensfabrik.de: ACL location not specified for domain www.rubensfabrik.de in ./rubensfabrik.de/getssl.cfg
getssl: rubensfabrik.de: exiting due to config errors

Auszug aus der ./rubensfabrik.de/getssl.cfg:
ACL=(
"ftp:${FTP_USER}:${FTP_PASSWD}:${DOMAIN}:.well-known/acme-challenge")

**Struktur auf dem Pi:**

pi@Xcloud-server:~ $
      -he/getssl
      -he/rubensfabrik.de
                  -he/rubensfabrik.de/getssl.cfg   ( nach anleitung editiert )
       -he/run.sh   (nach anleitung editiert) 
       -he/upload_to_kis.pl
 

Kannst Du helfen ?

**Comment by mklemme1** [comment]
Hallo,
In SANS definierst Du die Domains.
in ACL muss es dann pro Domäne eine Zeile geben.
Stimmt die Zahl in beiden Variablen überein?

Grüße
  M

**Comment by Don-Sheerwood** [comment]
Hallo
Wenn ich es richtig lese war mein Fehler das SANS explizit "zusätzliche Domains" meint. Ich brauche nur rubensfabrik.de zum testen. Also habe ich "SANS" nun in der /rubenfabrik.de/getssl.cfg ausgeschaltet und ein Zertifikat wurde erstellt. SCHRITT NACH VORNE. DANKE! 

**Ich hatte danach noch einen Fehler in der FTP Konfiguration. run.sh konnte nicht via FTP hochladen und hat abgebrochen und jetzt kam beim erneuten aufruf von "run.sh" der Fehler:** 

-----------------------------
sudo bash ./run.sh
Sun 24 Jun 11:44:17 UTC 2018
rubensfabrik.de: no certificate obtained from host
Registering account
Verify each domain
Verifying rubensfabrik.de
copying challenge token to ftp:FTP-ACCOUNT:PASSWORD:rubensfabrik.de:/.well-known/acme-challenge/ENCRYPTED KEY TOKEN
Local directory now /home/pi/rubensfabrik.de/tmp
Pending
Verified rubensfabrik.de
Verification completed, obtaining certificate.
Certificate saved in ./rubensfabrik.de/rubensfabrik.de.crt
The intermediate CA cert is in ./rubensfabrik.de/chain.crt
getssl: rubensfabrik.de - certificate obtained but certificate on server is different from the new certificate
-----------------------------
**Das Webverzeichnis auf HostEurope /.well-known/acme-challenge ist leer**

**Ruft man abermals run.sh auf, kommt:**
-----------------------------
sudo bash ./run.sh
Sun 24 Jun 11:53:28 UTC 2018
rubensfabrik.de: no certificate obtained from host
rubensfabrik.de: certificate is valid for more than 30 days (until Sep 22 10:44:42 2018 GMT)
-----------------------------

**Ich stell mich bestimmt total blöd an aber kannst Du nochmal helfen ?**

**Comment by mklemme1** [comment]
Hallo, 

der Ablauf ist soweit korrekt.
`getssl` startet als vorletztes das beiliegende Skript `upload_to_kis.pl`.
`upload_to_kis.pl` lädt die Zertifikate hoch.
HostEurope startet aber nicht augenblicklich den Server.
Daher meldet `gettssl`, das das neue Zertifikat noch nicht aktiv ist.

`getssl` erneuert die Zertifikate nur, wenn sie bald ablaufen.
Daher endet der zweite Aufruf sofort.

Sind die Zertifikate denn im KIS angekommen?
Du kannst es dort nachsehen.
Wenn nein, könntest Du in `run.sh` `./getssl` auskommentieren und `./upload_to_kis.pl`   einsetzen und es nochmal versuchen.

Grüße
  M

**Comment by Don-Sheerwood** [comment]
Guten Abend. Danke für die Hilfe.
Nein die Zertifikate sind nicht angekommen. Trotzdem bin ich ein Stück weiter:
Bin vorgegangen wie du gesagt hast: getssl raus .upload_to_kis.pl rein. 
Fehler: 
pi@cloud-server:~ $ sudo bash run.sh
Sun 24 Jun 17:23:20 UTC 2018
rubensfabrik.de/domainchain.crt not found at ./upload_to_kis.pl line 22.

im Verzeichnis rubenfabrik.de gibt es aber nur diese Dateien:

pi@cloud-server:~/rubensfabrik.de $ ls
archive  chain.crt  getssl.cfg  rubensfabrik.de.crt  rubensfabrik.de.csr  rubensfabrik.de.key
Hab ich irgendwo eine Variable vergessen?

**Comment by Don-Sheerwood** [comment]
Huhu, 
hab es selber hinbekommen. Ein ./getssl -f -u -w . "$KIS_DOMAIN" hat geholfen. 
Nun hat das Verzeichnis /rubensfabrik alle Dateien. 

Jetzt kommt der Fehler:
sudo bash run.sh

Sun 24 Jun 17:54:58 UTC 2018
Upload nicht erfolgreich at ./upload_to_kis.pl line 59.

**Comment by mklemme1** [comment]
Hallo,
Versuche, den URL direkt im Browser zu öffnen:
`https://kis.hosteurope.de/administration/webhosting/admin.php?kdnummer=XXX&passwd=YYY`
Dann siehst Du, ob es an den Zugangsdaten liegt.
`KIS_KDNUMMER` ist nicht die Kundennummer, sondern der Benutzername des KIS.

Grüße
M

**Comment by Don-Sheerwood** [comment]
Hey,
hier bekomme ich "Ungültiger Login" Benutzer und Pass stimmen aber.

**Comment by mklemme1** [comment]
Okay, dann hast Du vielleicht ein Passwort mit Sonderzeichen, die man so nicht in die URL schreiben kann.

Ich habe die Ausgabe im Fehlerfall von  `upload_to_kis.pl` erweitert.
Bitte lade es neu runter und probiere es noch einmal.

**Comment by Don-Sheerwood** [comment]
Hmmm, 
bekomme jetzt den Quellcode in der Shell angezeigt. Hier die ersten Zeilen. 


    <link href="/includes/login_faceLift.css" rel="stylesheet" type="text/css">
    <meta content="sYttps96JGkKGPuh2UJbUo_p7UubR180FK7lVOufnNI" name="google-site-verification">
    <meta content="1 day" name="revisit-after">
    <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <title>KIS Login</title>

</head>
<body>
        <div id="banner-kis"></div>
        <div id="content_wrapper">

            <div class="main_wrapper toast hide">
                <div class="error">
    <div class="spacer-h10px">&nbsp;</div>
    <div class="produktbox-1er-raster">
      <div class="spacer-v10px">&nbsp;</div>
      <p>Ung&uuml;ltiger Login. Bitte beachten Sie: Nach drei falschen Eingaben sperren wir aus Sicherheitsgründen Ihren Account.</p>
      <div class="spacer-v10px">&nbsp;</div>

**Comment by Don-Sheerwood** [comment]
Hab nochmal bei HE nachgeschaut: ein Sonderzeichen, eine Zahl und ein Großbuchstabe sind pflicht bei der Passwortvergabe :-(

**Comment by psysmile** [comment]
Probiere es mal mit einem Punkt als Sonderzeichen. Vielleicht klappt das. Ein Versuch ist es Wert.

**Comment by mklemme1** [comment]
Guter Hinweis, @psysmile.
@Don-Sheerwood, hast Du das Passwort in run.sh in einfache Anführungszeichen gesetzt?
Die Rückmeldung der Webseite ist ja eindeutig: 

> Ung&uuml;ltiger Login. Bitte beachten Sie: Nach drei falschen Eingaben sperren wir aus Sicherheitsgründen Ihren Account.

Daher würde ich mich nach jedem Fehlversuch im Browser einmal anmelden!

**Comment by Don-Sheerwood** [comment]
Wenn ich einen Punkt nehme kommt jetzt:

sudo bash ./run.sh
Mon 25 Jun 08:31:08 UTC 2018
unerwarteter HTTP Antwort-Code 302:  at ./upload_to_kis.pl line 55.

So sieht es in der run.sh aus. Habe Deine lediglich ausgefüllt. 
######## Configuration
# Password to HostEurope's admin website KIS
export KIS_PASSWD='XxX.XxxX1234'
# login name for KIS
export KIS_KDNUMMER='XxxxXxxx'
# WebPack ID
export KIS_WP_ID='WEBPACK ID'
# domain to be equipped
export KIS_DOMAIN='rubensfabrik.de'
# FTP user to this domain, in order to upload challenge files
export FTP_USER=FTP-USERNAME
# Password to FTP user
export FTP_PASSWD=FTP-PASSWORT

Browseranmeldung: ja habe ich gesehen.

**Comment by mklemme1** [comment]
Hallo,
Ist das Zertifikat denn hochgeladen?

Ich habe das Skript gerade noch einmal hier probiert, ohne Probleme.
Ich kann mir auch nicht vorstellen, dass Du ein anderes KIS hast als ich. :-S

**Comment by Don-Sheerwood** [comment]
Du meinst via FTP? Nein. Nix hochgeladen - aber FTP User und Pass stimmen.  Aber wo Du es gerade sagst: 
Müssen die Werte in export FTP_USER und export FTP_PASSWD in der run.sh nicht auch in einem einfachen Anführungszeichen stehen? Ich habe direkt Deine Datei übernommen und dachte dass das so i.o. ist.

Ein anderes KIS ?? Keine Ahnung. Glaube ich auch nicht.

**Comment by mklemme1** [comment]
Ich fragte, ob `upload_to_kis.pl` die Zertifikate ins KIS hochgeladen hat.

Die einfachen Anführungszeichen werden nur benötigt, wenn Werte Sonderzeichen enthalten.

**Comment by Don-Sheerwood** [comment]
Sorry. Hab ich falsch verstanden. Im KIS unter "Sicherheit & SSL -> SSL administrieren" ist unter der Domain rubensfabrik.de nichts eingetragen. :-( 

Und wenn ich das Upload Script über die run.sh starte kommt weiterhin: 
sudo bash ./run.sh
unerwarteter HTTP Antwort-Code 302: at ./upload_to_kis.pl line 55.

Die Webpack ID ist doch die 5 stellige Nummer, richtig ? 
Ich weiß nicht mit meinem sehr begrenzen Wissen wie und wo ich schauen soll um das Problem einzugrenzen.

**Comment by mklemme1** [comment]
Hallo

Die KIS_WP_ID ist die Vertragsnummer der Webseite
Du findest sie im KIS unter Produktverwaltung->Webhosting.
oder Produktverwaltung->Webhosting, Paket auswählen ->Allgemeines, dort "Paketname"
Bei mir ist sie 7-stellig.

Du kannst auch einfach die von getssl erzeugten Dateien nehmen und sie alle 60 Tage manuell im KIS hochladen.

**Comment by Don-Sheerwood** [comment]
Letzeres war es! Ich hatte die Webpack ID genommen. Mit der Vertragsnummer geht es nun!!! Danke. 
Für rubensfabrik.de wurde nun ein globales Zertifikat im KIS erstellt. 

Wenn ich jetzt für einen andere Domain xyz.com die Schritte wiederhole wird ein neues GLOBALES Zertifikat im KIS erstellt und rubensfabrik.de überschrieben. :-( Eigentlich sollte ja rubensfabrik.de bestehen bleiben und xyz.de hinzugefügt werden. Eine Idee? Oder sollen alle Domains in einer einzigen getssl.cfg verarbeitet? 

Sorry für die blöden Fragen.

**Comment by mklemme1** [comment]
Erstmal Glückwunsch zur verschlüsselten Webseite!

Pro Vertrag kann man bei HE ein globales Zertifikat hochladen.
Mit den Parametern `SANS` und `ACL` in `gettssl.cfg` kannst Du in dem globalen Zertifikat mehrere Webseiten abdecken (wir sprachen anfangs bereits darüber).

Du kannst aber auch pro Webseite ein eigenes Zertifikat hochladen.
Dazu müsstet Du in `upload_to_kis.pl` den Parameter `v_id` setzen wie für die jeweilige Webseite nötig.

**Comment by mklemme1** [comment]
Hallo,
Ich habe jetzt den Upload für einzelne Webseiten eingebaut in `run.sh` und `upload_to_kis.pl`.
Du musst in `run.sh` eine Variable `KIS_V_ID` definieren.
Du könntest also mehrere `run.sh` haben, die verschiedene Webseiten bedienen.

Bitte teste das mal und lass mich wissen, ob es funktionert!

**Comment by Don-Sheerwood** [comment]
Hey, 
funktioniert wunderbar. Ich bleibe aber bei dem globalem Zertifikat für alle weiteren domains. Oder spricht da was gegen? 
Ich musste noch in der in der getssl.cfg das ändern:
RELOAD_CMD="upload_to_kis.pl"     =>        RELOAD_CMD="./upload_to_kis.pl"
dann lief die run.sh mit mehreren Domains ohne Fehler durch. 

Habe hier bei Dir viel gelernt. Danke für Deine Mühe. Lass mich noch ein wenig testen und das Skipt ein wenig besser verstehen. Melde mich auf jeden Fall zurück.

**Comment by mklemme1** [comment]
Hallo, 
Bei einem gemeinsamen Zertifikat könnte der Benutzer der zweiten Webseite verwirrt sein, dass er im Zertifikat den Namen der ersten Webseite sieht.
