### ISSUE TITLE
Problems with username and login

### ISSUE THREAD

**Issue by Ghoschdi** [mklemme1/hosteurope-letsencrypt#4]
Hi,

first of all thanks for the amazing script and good howto. Everything works until the upload script is invoked and tries to login to KIS, which fails with the usual "invalid login, 3 tries..." message. 
I also tried to login manually via browser URL incl. changing the username & password multiple times back and forth. When i copy the username & password from the generated URL to the respective form fields, the login works, so I am really puzzled what the issue can be. Are there any known restrictions to certain webpacks or older contracts?

The script is hosted on an Ubuntu 14.04 LTS and I verified all the variables, including the webpack/contract ID multiple times. So I appreciate any hints / ideas.

Thanks!

**Comment by mklemme1** [comment]
Hallo
Could you try to set a password without 'unusual' characters?

  Michael

Am 28. Juli 2018 18:40:09 MESZ schrieb Stefan <notifications@github.com>:

**Comment by Ghoschdi** [comment]
Hey, thanks for the swift response!

I have password that is in form of Xxx.123 and no german umlaut.

Just out of curiosity, are you definitely able to login manually via the url with the variables attached? I tried with all my accounts and none of them works.

Appreciate your help!

Stefan

**Comment by mklemme1** [comment]
Well, I cannot at this moment in time.
And my script stopped working as well.

The [FAQ page](https://www.hosteurope.de/faq/kis/allgemeines0/wie-funktioniert-die-automatische-anmeldung-im-kis/) relating to this feature is currently unavailable.
Let's see how this develops...

**Comment by Ghoschdi** [comment]
That explains my problems. Not the first time HE breaks a fundamental functionality and I am more and more tempted to walk away because of several changes in recent years.

Appreciate your work anyhow and hope this gets sorted

**Comment by mklemme1** [comment]
Hallo Stefan

HostEurope Support confirmed that they have removed the auto-login via 
the URL parameters "for security reasons".
I therefore need to find a different approach for logging in.

**Comment by Ghoschdi** [comment]
Appreciate the swift reply.

Just an idea. How about logging into the page via CURL first, store the cookie and then use it to submit the form on the SSL page by reading the cookie via the SETOPT CURLOPT_COOKIEJAR and CURLOPT_COOKIEFILE?

**Comment by Ghoschdi** [comment]
I tinkered a bit with the upload script. For testing I simply added 
`system "curl -F 'kdnummer=".$kdnummer."' -F 'passwd=".$passwd."' --cookie-jar ./cookie.txt https://kis.hosteurope.de";`

That generates the cookie and was able to read that with
`$curl->setopt(WWW::Curl::Easy::CURLOPT_COOKIEFILE(), "./cookie.txt");` in the original CURL command. 
Moved on to remove the $kdnummer & $passwd from the URL, so my URL var looks like `my $url = "https://kis.hosteurope.de/administration/webhosting/admin.php";`

With that it seems like it is able to upload the certificate, as it posted those on an account, that had none so far. KIS now shows that I set a global SSL, but i cannot test it for the first time replication. 

On the account that already had a SSL in place, it also worked and the new end date is reflected in KIS Backend.

Hope that helps,
Stefan

**Comment by Ghoschdi** [comment]
Another update: Interestingly HE has NOW implemented a reCaptcha to prevent script logins to their backend. They are really trying hard to get rid of folks that want to automate.

**Comment by Ghoschdi** [comment]
Alright, final update: HE will not get rid of their new captcha for "security reasons". So i modified the run.sh to zip and send me the certificates via mail after the cron got the update from LE. At least this triggers me automatically...Still a lot of domains to manually update now.


I will polish the code a bit later, but for now that works.
```
./getssl -u -w . "$KIS_DOMAIN" 
zip ./$KIS_DOMAIN/$KIS_DOMAIN.zip -j ./$KIS_DOMAIN/domainchain.crt ./$KIS_DOMAIN/$KIS_DOMAIN.key
mailx -a ./$KIS_DOMAIN/$KIS_DOMAIN.zip  -s "New certificate for $KIS_DOMAIN" xxx@xxx.xx< /dev/null
rm ./$KIS_DOMAIN/$KIS_DOMAIN.zip
```

Hope that helps a bit and i will close the issue, as the problem is not caused by your script, but HE's unfortunate stance towards automation.

**Comment by Ghoschdi** [comment]
Final script, which tests if new certs have been issued and sends mails accordingly. Everything will run in a cron job every month now.
```
######## End of Configuration

if ! ./getssl -u -w . "$KIS_DOMAIN" | grep -q 'valid'; then
        zip ./$KIS_DOMAIN/$KIS_DOMAIN.zip -j ./$KIS_DOMAIN/domainchain.crt ./$KIS_DOMAIN/$KIS_DOMAIN.key
        mailx -a ./$KIS_DOMAIN/$KIS_DOMAIN.zip  -s "New certificate for $KIS_DOMAIN" xxx@xxx.xx< /dev/null
        rm ./$KIS_DOMAIN/$KIS_DOMAIN.zip
fi
#end
```
