### ISSUE TITLE
Can't login at line 29

### ISSUE THREAD

**Issue by basdl** [mklemme1/hosteurope-letsencrypt#5]
Hi,

i wanted to update my certificates. Unfortunately, it does not work anymore. The script returns with

`Error POSTing https://sso.hosteurope.de/api/app/v1/login: Unauthorized at upload_to_kis.pl line 29.`

I double checked my credentials and everything. Has anyone else the same issue?

**Comment by mklemme1** [comment]
Yes, same here.

They have now added a recaptcha - once more.

I am afraid we all now need to upload the keys again manually.  :-(

**Comment by Ghoschdi** [comment]
Strange, I do not have a captcha, but it seems they changed the endpoint of the login api?

**Comment by mklemme1** [comment]
I see one in the lower right corner.
A Recaptcha parameter is now sent along for the login call.

**Comment by Ghoschdi** [comment]
True, that was blocked by my browser config, apologies. Hm, bad luck...back to automailing my certs on renewal. Thanks for your script though, was the only light in HE's endless dark venture to make server admin's life harder.

**Comment by johannesmik** [comment]
So the script does not work as intended at the moment? It would be a good idea to update the README then.
