### ISSUE TITLE
Idea/Request: Using DNS-challenge

### ISSUE THREAD

**Issue by rankerson** [mklemme1/hosteurope-letsencrypt#6]
Hallo Michael,

habe gerade Dein Script entdeckt (über den Artikel von andydunkel.net). Bin auch insofern ein genervter hosteurope-Kunde, weil ich alle drei Monate manuell die Zertifikate erzeugen muss und öfter mal (also alle 3 Monate) auf der Suche nach Automatisierung. Nun hat sich hier ja was getan, was ja auch Dein Script zeigt, nur arbeiten bisher alle mit den Datei-challenges, was in meinem Fall nicht funktioniert, weil ich subdomains nutze, die per CNAME unmittelbar umgeleitet werden; das würde das Handling mit Dateien noch komplizierter machen. Deshalb arbeite ich mit DNS-Challenges.

Meinst Du das Script wäre insofern erweiterbar, dass es auch mit DNS Challenges arbeitet? Ich habe zur DNS Aktualisierung folgendes von @ChristianUlbrich gefunden: [https://gist.github.com/ChristianUlbrich/6412229](https://gist.github.com/ChristianUlbrich/6412229).

Leider reichen meine Kenntnisse für die Kombination von beidem nicht aus. Denkst Du so etwas ist grundsätzlich möglich und hättest Du oder jemand anders vielleicht Lust? :-)

Schöne Grüße

Ranki

**Comment by mklemme1** [comment]
Hallo Ranki

Das Skript nutzt den gleichen Weg zur Authentifizierung wie mein Programm. 
Hosteurope hat ihn abgeschaltet. 
Daher gehen beide Skripte nicht mehr. 
Ein neuer Weg ist mir nicht bekannt. 

Grüße
  Michael

**Comment by rankerson** [comment]
Hallo Michael,

achso, logisch; daran hakt es dann schon ... *grrr* - Naja, danke Dir für die rasche Antwort. Ich glaube so schnell wird hosteurope dann da nix anbieten und ich könnte mir sogar vorstellen, dass sie es aus so einem Grund auch nun mit einem Captcha gesichert haben ... *grrr*.

Vielen Dank und schöne Grüße

Ranki
